toolchains:
  gcc_all:
      - spec: "%c=gcc@14.2"
        when: "%c"
      - spec: "%cxx=gcc@14.2"
        when: "%cxx"
      - spec: "%fortran=gcc@14.2"
        when: "%fortran"
  cce_all:
      - spec: "%c=cce@19.0.0"
        when: "%c"
      - spec: "%cxx=cce@19.0.0"
        when: "%cxx"
      - spec: "%fortran=cce@19.0.0"
        when: "%fortran"
  intel_all:
      - spec: "%c=intel-oneapi-compilers@2025.0.4"
        when: "%c"
      - spec: "%cxx=intel-oneapi-compilers@2025.0.4"
        when: "%cxx"
      - spec: "%fortran=intel-oneapi-compilers@2025.0.4"
        when: "%fortran"
  aocc_all:
      - spec: "%c=aocc@5.0.0"
        when: "%c"
      - spec: "%cxx=aocc@5.0.0"
        when: "%cxx"
      - spec: "%fortran=aocc@5.0.0"
        when: "%fortran"
  